version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context: my-context

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout









      - run: mvn clean deploy --batch-mode --settings .circleci/mvn-settings.xml
        # | grep -Ev "Download(ing|ed)"
