version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context: my-context

jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ find . -type f -regex ".*/pom.xml" -exec cat {} \; | checksum }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - run: mvn -s .circleci/mvn-settings.xml clean | grep -Ev "Download(ing|ed)"
      - run: mvn -s .circleci/mvn-settings.xml install | grep -Ev "Download(ing|ed)"
      - run: mvn -s .circleci/mvn-settings.xml deploy -DskipTests -Dmaven.install.skip=true
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
